const PROJECTS_DATA = [
  {
    title: 'Music App (in progress)',
    keywords: 'ReactJS, Redux, SPA',
    id: 1,
    imgSrc: '/img/music-app.png',
    button: 'Check this project on GitHub',
    link: '',
    gitHubLink: 'https://github.com/KittySaur/music-app',
  },
  {
    title: 'Memory card game',
    keywords: 'JavaScript, WebPack, HTML/CSS',
    id: 2,
    imgSrc: '/img/memory-game.png',
    button: 'Check this project on GitHub',
    link: 'https://memory-card-game-by-z.netlify.app',
    gitHubLink: 'https://github.com/KittySaur/card_game',
  },
  {
    title: 'Online rock-scissors-paper game',
    keywords: 'JavaScript, AJAX, SPA, API, HTML/CSS',
    id: 3,
    imgSrc: '/img/rock-scissors-paper.png',
    button: 'Check this project on GitHub',
    link: 'https://kittysaur.github.io/online-rock-scissors-paper-game/',
    gitHubLink: 'https://github.com/KittySaur/online-rock-scissors-paper-game',
  },
  {
    title: 'Weather widget',
    keywords: 'JavaScript, AJAX, API, HTML/CSS',
    id: 4,
    imgSrc: '/img/weather-widget.png',
    button: 'Check this project on GitHub',
    link: 'https://kittysaur.github.io/weather-app/',
    gitHubLink: 'https://github.com/KittySaur/weather-app',
  },
  {
    title: 'Simple JS games',
    keywords: 'Vanilla JavaScript, Responsive design, HTML/CSS',
    id: 5,
    imgSrc: '/img/simple-js.png',
    button: 'Check this project on GitHub',
    link: 'https://kittysaur.github.io/simple-js-game/index.html',
    gitHubLink: 'https://github.com/KittySaur/simple-js-game',
  },
  {
    title: 'Responsive furniture store website',
    keywords: 'Responsive design, HTML/CSS, SASS',
    id: 6,
    imgSrc: '/img/furniture-landing.png',
    button: 'Check this project on GitHub',
    link: 'https://kittysaur.github.io/furniture-template-site/',
    gitHubLink: 'https://github.com/KittySaur/furniture-template-site',
  },
]

export default PROJECTS_DATA
